-- +goose Up
CREATE TABLE feeds(id UUID PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, name TEXT NOT NULL, url TEXT NOT NULL UNIQUE, user_id UUID NOT NULL, CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE);
ALTER TABLE feeds ADD COLUMN last_fetched_at TIMESTAMP;

-- +goose Down

ALTER TABLE feeds DROP COLUMN last_fetched_at; 
DROP TABLE feeds;
